spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200
      connection-timeout: 10s
  datasource:
    url: jdbc:mysql://localhost:3306/oj?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type:  com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
    # 设置静态文件路径，js,css等
    mvc:
      static-path-pattern: /static/**

# mybatis-plus
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8082


# canal配置
canal:
  host: localhost # 单机用
  port: 11111
  destination: code #环境共用参数
  username:
  password:
  subscribe: # 订阅的表
  zk-server-list: X.X.X.X:2181,X.X.X.X:2181 # 高可用

logging:
  level:
    cn.sdutacm.*: info
